eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
server:
  port: 9903
spring:
  application:
    name: order
  profiles:
    active: jdbc
  datasource:
    url: jdbc:mysql://localhost/orders?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 19900420
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

